// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Action = { "type": "DrawFromDeck" } | { "type": "TakeDiscard" } | { "type": "Flip", slot: number, } | { "type": "Swap" } | { "type": "Keep" } | { "type": "NextHole" };
