// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Action } from "./Action";
import type { Difficulty } from "./Difficulty";

export type ClientMsg = { "type": "CreateRoom", name: string, } | { "type": "JoinRoom", code: string, name: string, } | { "type": "Rejoin", code: string, token: string, } | { "type": "AddBot", difficulty: Difficulty, } | { "type": "RemoveSeat", seat: number, } | { "type": "StartMatch", holes: number, } | { "type": "Act", action: Action, } | { "type": "Ping" };
