// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LobbySeat } from "./LobbySeat";

export type LobbyState = { code: string, seats: Array<LobbySeat>, host: number, you: number, started: boolean, };
