// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SeatConfig } from "./SeatConfig";

export type MatchConfig = { seats: Array<SeatConfig>, holes: number, };
