// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SlotView } from "./SlotView";

export type SeatView = { name: string, is_bot: boolean, grid: Array<SlotView>, };
