// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Card } from "./Card";
import type { DrawSource } from "./DrawSource";

export type TurnState = { "type": "AwaitDraw" } | { "type": "AwaitFlip", drawn: Card, source: DrawSource, } | { "type": "AwaitResolve", drawn: Card, source: DrawSource, flipped: number, };
