// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ErrorCode = "RoomNotFound" | "RoomFull" | "MatchAlreadyStarted" | "MatchNotStarted" | "NotHost" | "BadToken" | "BadAction" | "BadRequest" | "Kicked";
