// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Difficulty } from "./Difficulty";

export type LobbySeat = { name: string, difficulty: Difficulty | null, connected: boolean, };
