// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PhaseView = { "type": "Playing" } | { "type": "HoleComplete", scores: Array<number>, 
/**
 * Optimal pairing per seat, as slot-index pairs, for highlighting.
 */
pairings: Array<Array<[number, number]>>, } | { "type": "MatchComplete", winners: Array<number>, };
