// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ErrorCode } from "./ErrorCode";
import type { Event } from "./Event";
import type { LobbyState } from "./LobbyState";
import type { PlayerView } from "./PlayerView";

export type ServerMsg = { "type": "RoomJoined", code: string, seat: number, token: string, } | { "type": "Lobby", state: LobbyState, } | { "type": "Events", events: Array<Event>, } | { "type": "State", view: PlayerView, } | { "type": "Error", code: ErrorCode, message: string, } | { "type": "Pong" };
