// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Card } from "./Card";

/**
 * Public record of something that happened. Events never contain hidden
 * information (the deck flip is public in this variant), so a single event
 * stream can be broadcast to every player and spectator unredacted.
 */
export type Event = { "type": "HoleDealt", hole: number, starting_seat: number, discard_start: Card, } | { "type": "TurnStarted", seat: number, } | { "type": "DrewFromDeck", seat: number, card: Card, } | { "type": "TookDiscard", seat: number, card: Card, } | { "type": "Flipped", seat: number, slot: number, card: Card, } | { "type": "Swapped", seat: number, slot: number, placed: Card, discarded: Card, } | { "type": "Kept", seat: number, slot: number, discarded: Card, } | { "type": "HoleEnded", hole: number, scores: Array<number>, totals: Array<number>, } | { "type": "MatchEnded", totals: Array<number>, winners: Array<number>, };
