// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ActionKind } from "./ActionKind";
import type { Card } from "./Card";
import type { PhaseView } from "./PhaseView";
import type { SeatView } from "./SeatView";
import type { TurnState } from "./TurnState";

/**
 * Everything one viewer may know about the match. Serializing an opponent's
 * or spectator's view never leaks a `Hidden` card.
 */
export type PlayerView = { 
/**
 * The seat this view was redacted for; `None` = spectator.
 */
viewer: number | null, seats: Array<SeatView>, deck_len: number, discard_top: Card | null, discard_len: number, current: number, turn: TurnState, hole_number: number, holes_total: number, totals: Array<number>, 
/**
 * Completed holes: `score_history[hole][seat]`.
 */
score_history: Array<Array<number>>, phase: PhaseView, 
/**
 * Action kinds the viewer may take right now (empty when not their turn).
 */
legal_actions: Array<ActionKind>, };
