// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RuleError = { "type": "NotYourTurn" } | { "type": "WrongPhase" } | { "type": "BadSeat" } | { "type": "BadSlot" } | { "type": "SlotFrozen" } | { "type": "MatchOver" };
