// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Card } from "./Card";

/**
 * What one viewer can see of a single card slot.
 */
export type SlotView = { "type": "Hidden" } | { "type": "Peeked", card: Card, } | { "type": "FaceUp", card: Card, };
